Added new tests for two consecutive adjoint runs
mdolab/adflow pull request #362
Opened 2024-08-30 21:30 UTC by sabakhshi

## Purpose

## Expected time until merged

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

2024-09-01 16:36 UTC, marcomangano requested changes
See my comments below, I don't think we should add separate reference results for the second sensitivity analysis, am I missing anything?

2024-09-01 16:36 UTC, marcomangano commented on tests/reg_tests/reg_test_utils.py
> +    handler.root_add_dict("Eval Functions Sens 2:", funcsSens, rtol=rtol, atol=atol)
Shouldn't we compare the second run against the values of the first run `Eval Functions Sens`? I don't see the point of adding this if the point of the test is to make sure that the adjoint converges to the same result (within a tolerance)

2024-09-01 16:36 UTC, marcomangano commented on tests/reg_tests/reg_test_utils.py
> +
This is probably causing the black and flake8 error

2024-09-01 16:36 UTC, marcomangano commented on tests/reg_tests/refs/adjoint_euler_scalar_jst_tut_wing.json
> +    "Eval Functions Sens 2:": {
As I mention below, I don't think we should add this, ideally the only thing added to the `.json` files is the `Adjoint States` entry

2024-09-23 21:31 UTC, marcomangano requested changes
The added tests look good, I only think the `.json` files need to be cleaned up - see my comment below

2024-09-23 21:31 UTC, marcomangano commented on tests/reg_tests/refs/adjoint_euler_scalar_jst_tut_wing.json
> +    "Adjoint States": 0.0,
This entry should be the only one changing in the `.json` files. There is no point changing the reference values for this PR, especially if the training is done on a local machine.

2024-09-23 21:33 UTC, marcomangano commented
Also note that the black and flake8 tests are failing, please fix them. Remember that we currently use `black==23.1.0` and custom `flake8` settings

2024-11-06 21:35 UTC, sabakhshi commented
Everything should be addressed. Re-requesting your review.

2024-11-08 18:35 UTC, marcomangano approved these changes
Nice cleanup, thanks!

2024-11-13 19:59 UTC, lamkina approved these changes

2024-11-13 19:59 UTC, merged